[package]
name = "hopcroft-karp"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fxhash = "0.2.1"

[dev-dependencies]
rand = "0.8.5"
rand_chacha = "0.3.1"
